project:
  type: website

website:
  title: "Stephany's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects
        text: Projects
       


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



